/**
 * 
 */
package com.cwt.kafka.consumer.entity;

import java.util.Date;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Component
@DynamoDBTable(tableName = "metstaging")
public class MetEntity {

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String metId;

	@DynamoDBAttribute
	public String metJsonString;

	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
	public Date createdDate;
	
	@DynamoDBAttribute
	public boolean metFlag;

	public MetEntity() {
	}

	public String getMetId() {
		return metId;
	}

	public void setMetId(String metId) {
		this.metId = metId;
	}

	public String getMetJsonString() {
		return metJsonString;
	}

	public void setMetJsonString(String metJsonString) {
		this.metJsonString = metJsonString;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public boolean isMetFlag() {
		return metFlag;
	}

	public void setMetFlag(boolean metFlag) {
		this.metFlag = metFlag;
	}

	@Override
	public String toString() {
		return "MetEntity [metJsonString=" + metJsonString + ", metFlag=" + metFlag + "]";
	}

	public MetEntity(String metJsonString, boolean metFlag) {
		this.metJsonString = metJsonString;
		this.metFlag = metFlag;
	}

	

}